/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Alterar;

import SQL.Conexion;
import static SQL.Conexion.conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class AlterarClienteAtiendeMesa extends javax.swing.JFrame {

    /**
     * Creates new form AlterarClienteAtiendeMesa
     */
    public AlterarClienteAtiendeMesa() {
        initComponents();
        
        opcion.removeAllItems();
        meseroIDAgregar.removeAllItems();
        mesaID.removeAllItems();
        opcion.addItem("Agregar");
        opcion.addItem("Modificar");
        opcion.addItem("Eliminar");
        meseroIDModificar.removeAllItems();
        mesaIDModificar.removeAllItems();
        meseroIDEliminar.removeAllItems();
        mesaIDEliminar.removeAllItems();
        modificarMeseroC.removeAllItems();
        modificarMesaC.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void actualizarMeseroIDA(){
        meseroIDAgregar.removeAllItems();
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "select * from Empleado where PuestoID = 3";
            rs = s.executeQuery(query);
            while(rs.next()){
                meseroIDAgregar.addItem(rs.getString("EmpleadoID"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar mesa");
            System.out.println(ex);
        }
    }
    public void actualizarMeseroIDEliminar(){
        meseroIDEliminar.removeAllItems();
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "select * from Empleado where PuestoID = 3";
            rs = s.executeQuery(query);
            while(rs.next()){
                meseroIDEliminar.addItem(rs.getString("EmpleadoID"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar mesero");
            System.out.println(ex);
        }
    }
    
    public void agregarMesaAtentida(){
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "INSERT INTO MeseroAtiendeMesa\n" +
                            "VALUES ("+mesaID.getSelectedItem()+","+meseroIDAgregar.getSelectedItem()+")";
            int a = s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Agregar mesa atendida ha sido un exito");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar mesa atendida");
            System.out.println(ex);
        }
    }
    public void actualizarMeseroIDEliminarModificar(){
        meseroIDModificar.removeAllItems();
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "select * from Empleado where PuestoID = 3";
            rs = s.executeQuery(query);
            while(rs.next()){
                meseroIDModificar.addItem(rs.getString("EmpleadoID"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar mesero");
            System.out.println(ex);
        }
    }
    public void actualizarMeseroIDModificarAgregar(){
        modificarMeseroC.removeAllItems();
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "select * from Empleado where PuestoID = 3";
            rs = s.executeQuery(query);
            while(rs.next()){
                modificarMeseroC.addItem(rs.getString("EmpleadoID"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar mesa");
            System.out.println(ex);
        }
    }
    //Modificar
    public void ModificarMesaAtendida(){
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "Delete FROM MeseroAtiendeMesa where EmpleadoID ="+meseroIDModificar.getSelectedItem()+" AND MesaID = "+mesaIDModificar.getSelectedItem();
            int a = s.executeUpdate(query);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al modificar mesa atendida");
            System.out.println(ex);
        }
        try {
            s = conexion.createStatement();
            String query = "INSERT INTO MeseroAtiendeMesa\n" +
                            "VALUES ("+modificarMesaC.getSelectedItem()+","+modificarMeseroC.getSelectedItem()+")";
            int a = s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Modificar mesa atendida ha sido un exito");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al modificar mesa atendida");
            System.out.println(ex);
        }
    }
    
    public void EliminarMesaAtentida(){
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "Delete FROM MeseroAtiendeMesa where EmpleadoID ="+meseroIDEliminar.getSelectedItem()+" AND MesaID = "+mesaIDEliminar.getSelectedItem();
            int a = s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Eliminar mesa atendida con exito");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar mesa atendida");
            System.out.println(ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        meseroIDAgregar = new javax.swing.JComboBox<>();
        mesaID = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        meseroIDModificar = new javax.swing.JComboBox<>();
        mesaIDModificar = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        modificarMeseroC = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        modificarMesaC = new javax.swing.JComboBox<>();
        comandaIDEliminar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        meseroIDEliminar = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        mesaIDEliminar = new javax.swing.JComboBox<>();
        RealizarAccion = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mesero Atiende Mesa");

        jLabel14.setText("ElegirOpcion");

        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opcion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(23, 23, 23)))
                .addGap(102, 102, 102))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Agregar");

        meseroIDAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        meseroIDAgregar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                meseroIDAgregarItemStateChanged(evt);
            }
        });

        mesaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mesaID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mesaIDItemStateChanged(evt);
            }
        });

        jLabel21.setText("MeseroID");

        jLabel22.setText("MesaID");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel19))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meseroIDAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meseroIDAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(mesaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Modificar");

        jLabel24.setText("MeseroID");

        jLabel25.setText("MesaID");

        meseroIDModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        meseroIDModificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                meseroIDModificarItemStateChanged(evt);
            }
        });

        mesaIDModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel28.setText("Modificar a:");

        jLabel29.setText("MeseroID");

        modificarMeseroC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modificarMeseroC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modificarMeseroCItemStateChanged(evt);
            }
        });

        jLabel30.setText("MesaID");

        modificarMesaC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meseroIDModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesaIDModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarMeseroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificarMesaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel23))
                .addGap(96, 96, 96))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(meseroIDModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(mesaIDModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(modificarMeseroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(modificarMesaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        comandaIDEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));

        jLabel20.setText("Eliminar");

        jLabel26.setText("MeseroID");

        meseroIDEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        meseroIDEliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                meseroIDEliminarItemStateChanged(evt);
            }
        });

        jLabel27.setText("MesaID");

        mesaIDEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout comandaIDEliminarLayout = new javax.swing.GroupLayout(comandaIDEliminar);
        comandaIDEliminar.setLayout(comandaIDEliminarLayout);
        comandaIDEliminarLayout.setHorizontalGroup(
            comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comandaIDEliminarLayout.createSequentialGroup()
                .addGroup(comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comandaIDEliminarLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel20))
                    .addGroup(comandaIDEliminarLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meseroIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesaIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        comandaIDEliminarLayout.setVerticalGroup(
            comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comandaIDEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(27, 27, 27)
                .addGroup(comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(meseroIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(comandaIDEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(mesaIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RealizarAccion.setText("Realizar");
        RealizarAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RealizarAccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RealizarAccionMouseEntered(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(RealizarAccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresar))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(comandaIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comandaIDEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(RealizarAccion)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(772, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==evt.SELECTED){
            switch(opcion.getSelectedIndex()){
                case 0:
                    actualizarMeseroIDA();
                    meseroIDEliminar.removeAllItems();
                    mesaIDEliminar.removeAllItems();
                    meseroIDModificar.removeAllItems();
                    mesaIDModificar.removeAllItems();
                    modificarMeseroC.removeAllItems();
                    modificarMesaC.removeAllItems();
                    meseroIDModificar.setEditable(false);
                    meseroIDModificar.setEnabled(false);
                    mesaIDModificar.setEditable(false);
                    mesaIDModificar.setEnabled(false);
                    meseroIDEliminar.setEditable(false);
                    meseroIDEliminar.setEnabled(false);
                    mesaIDEliminar.setEditable(false);
                    mesaIDEliminar.setEnabled(false);
                    modificarMeseroC.setEnabled(false);
                    modificarMeseroC.setEditable(false);
                    modificarMesaC.setEnabled(false);
                    modificarMesaC.setEditable(false);
                    meseroIDAgregar.setEditable(true);
                    meseroIDAgregar.setEnabled(true);
                    mesaID.setEnabled(true);
                    mesaID.setEditable(true);
                break;
                
                case 1:
                    actualizarMeseroIDEliminarModificar();
                    actualizarMeseroIDModificarAgregar();
                    mesaID.removeAllItems();
                    meseroIDEliminar.removeAllItems();
                    mesaIDEliminar.removeAllItems();
                    meseroIDAgregar.removeAllItems();
                    meseroIDModificar.setEditable(true);
                    meseroIDModificar.setEnabled(true);
                    mesaIDModificar.setEditable(true);
                    mesaIDModificar.setEnabled(true);
                    modificarMeseroC.setEnabled(true);
                    modificarMeseroC.setEditable(true);
                    modificarMesaC.setEnabled(true);
                    modificarMesaC.setEditable(true);
                    meseroIDAgregar.setEditable(false);
                    meseroIDAgregar.setEnabled(false);
                    mesaID.setEnabled(false);
                    mesaID.setEditable(false);
                    meseroIDEliminar.setEditable(false);
                    meseroIDEliminar.setEnabled(false);
                    mesaIDEliminar.setEditable(false);
                    mesaIDEliminar.setEnabled(false);
                break;

                case 2:
                    actualizarMeseroIDEliminar();
                    mesaID.removeAllItems();
                    meseroIDAgregar.removeAllItems();
                    meseroIDAgregar.removeAllItems();
                    meseroIDModificar.removeAllItems();
                    mesaIDModificar.removeAllItems();
                    modificarMeseroC.removeAllItems();
                    modificarMesaC.removeAllItems();
                    meseroIDModificar.setEditable(false);
                    meseroIDModificar.setEnabled(false);
                    mesaIDModificar.setEditable(false);
                    mesaIDModificar.setEnabled(false);
                    meseroIDAgregar.setEditable(false);
                    meseroIDAgregar.setEnabled(false);
                    mesaID.setEnabled(false);
                    mesaID.setEditable(false);
                    modificarMeseroC.setEnabled(false);
                    modificarMeseroC.setEditable(false);
                    modificarMesaC.setEnabled(false);
                    modificarMesaC.setEditable(false);
                    meseroIDEliminar.setEditable(true);
                    meseroIDEliminar.setEnabled(true);
                    mesaIDEliminar.setEditable(true);
                    mesaIDEliminar.setEnabled(true);
                break;
            }
        }
    }//GEN-LAST:event_opcionItemStateChanged

    private void mesaIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mesaIDItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==evt.SELECTED){
            
        }
    }//GEN-LAST:event_mesaIDItemStateChanged

    private void meseroIDAgregarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_meseroIDAgregarItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getStateChange()==evt.SELECTED){
            mesaID.removeAllItems();
            Conexion bd = new Conexion();
            ResultSet rs;
            Statement s;
            
            try {
                s = conexion.createStatement();
                String query = "select * from Mesas";
                rs = s.executeQuery(query);
                while(rs.next()){
                    mesaID.addItem(rs.getString("MesaID"));
                }
                query = "Select * from MeseroAtiendeMesa where EmpleadoID = "+meseroIDAgregar.getSelectedItem();
                rs = s.executeQuery(query);
                while(rs.next()){
                    mesaID.removeItem(rs.getString("MesaID"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al generar mesa");
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_meseroIDAgregarItemStateChanged

    private void RealizarAccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RealizarAccionMouseClicked
        // TODO add your handling code here:
        switch(opcion.getSelectedIndex()){
            case 0:
                agregarMesaAtentida();
                actualizarMeseroIDA();
            break;

            case 1:
                ModificarMesaAtendida();
                actualizarMeseroIDEliminarModificar();
                actualizarMeseroIDModificarAgregar();
            break;

            case 2:
                EliminarMesaAtentida();
                actualizarMeseroIDEliminar();
            break;
        }
    }//GEN-LAST:event_RealizarAccionMouseClicked

    private void RealizarAccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RealizarAccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RealizarAccionMouseEntered

    private void meseroIDEliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_meseroIDEliminarItemStateChanged
        // TODO add your handling code here:
        mesaIDEliminar.removeAllItems();
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "select * from MeseroAtiendeMesa where EmpleadoID = "+meseroIDEliminar.getSelectedItem();
            rs = s.executeQuery(query);
            while(rs.next()){
                mesaIDEliminar.addItem(rs.getString("MesaID"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar mesaID");
            System.out.println(ex);
        }
    }//GEN-LAST:event_meseroIDEliminarItemStateChanged

    private void meseroIDModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_meseroIDModificarItemStateChanged
        // TODO add your handling code here:
        mesaIDModificar.removeAllItems();
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        try {
            s = conexion.createStatement();
            String query = "select * from MeseroAtiendeMesa where EmpleadoID = "+meseroIDModificar.getSelectedItem();
            rs = s.executeQuery(query);
            while(rs.next()){
                mesaIDModificar.addItem(rs.getString("MesaID"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar mesaID");
            System.out.println(ex);
        }
    }//GEN-LAST:event_meseroIDModificarItemStateChanged

    private void modificarMeseroCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modificarMeseroCItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==evt.SELECTED){
            modificarMesaC.removeAllItems();
            Conexion bd = new Conexion();
            ResultSet rs;
            Statement s;
            
            try {
                s = conexion.createStatement();
                String query = "select * from Mesas";
                rs = s.executeQuery(query);
                while(rs.next()){
                    modificarMesaC.addItem(rs.getString("MesaID"));
                }
                query = "Select * from MeseroAtiendeMesa where EmpleadoID = "+modificarMeseroC.getSelectedItem();
                rs = s.executeQuery(query);
                while(rs.next()){
                    modificarMesaC.removeItem(rs.getString("MesaID"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al generar mesa");
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_modificarMeseroCItemStateChanged

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        AlterarMenu alt = new AlterarMenu();
        alt.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarClienteAtiendeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarClienteAtiendeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarClienteAtiendeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarClienteAtiendeMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarClienteAtiendeMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RealizarAccion;
    private javax.swing.JButton Regresar;
    private javax.swing.JPanel comandaIDEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> mesaID;
    private javax.swing.JComboBox<String> mesaIDEliminar;
    private javax.swing.JComboBox<String> mesaIDModificar;
    private javax.swing.JComboBox<String> meseroIDAgregar;
    private javax.swing.JComboBox<String> meseroIDEliminar;
    private javax.swing.JComboBox<String> meseroIDModificar;
    private javax.swing.JComboBox<String> modificarMesaC;
    private javax.swing.JComboBox<String> modificarMeseroC;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
