/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgregarProductosComanda;

import SQL.CapaPresentacion.Operaciones;
import SQL.Conexion;
import static SQL.Conexion.conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class GenerarComanda extends javax.swing.JFrame {
    //Para agregrar productos en comanda
    private String ComandaID;
    private String ProductIDin;
    private int Cantidadin;
    private String TipoProductoin;
    private int contador=0;
    
    //Para insertar comanda
    private String momandaIDin;
    private String meseroIDin;
    private String cajeroIDin;
    private String mesaIDin;
    private int contador2;
    
    /**
     * Creates new form GenerarComanda
     */
    public GenerarComanda() {
        initComponents();
        //agregar comanda
        ComandaInsert.setVisible(false);
        ProductoEncontrado.setVisible(false);
        ProductoEncontrado.setVisible(false);
        Conexion bd = new Conexion();
        contador2 = 0;
        Cantidad.setValue(1);
        ResultSet rs;
        Statement s;
        MesaID.removeAllItems();
        MeseroID.removeAllItems();
        CajeroID.removeAllItems();
        try {
            s = conexion.createStatement();
            String query = "SELECT MesaID FROM Mesas";
            rs = s.executeQuery(query);
            while (rs.next()) {
                MesaID.addItem(rs.getString("MesaID"));
            }
            query = "select EmpleadoID from Empleado where PuestoID = 4";
            rs = s.executeQuery(query);
            while (rs.next()) {
                CajeroID.addItem(rs.getString("EmpleadoID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GenerarComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Agregar productos a comanda
        BuscarComandaID.removeAllItems();
        ProductoID.removeAllItems();
        TipoProducto.removeAllItems();
        try {
            //Comanda
            s = conexion.createStatement();
            String query = "Select * from Comanda where not exists (select * from Ticket where Ticket.ComandaID = Comanda.ComandaID)";
            rs = s.executeQuery(query);
            while (rs.next()) {
                BuscarComandaID.addItem(rs.getString("ComandaID"));
            }
            //Tipo Producto
            s = conexion.createStatement();
            query = "select * from TipoProducto";
            rs = s.executeQuery(query);
            while (rs.next()) {
                this.TipoProducto.addItem(rs.getString("NombreTipoProducto"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GenerarComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MesaID = new javax.swing.JComboBox<>();
        MeseroID = new javax.swing.JComboBox<>();
        CajeroID = new javax.swing.JComboBox<>();
        AgregarComanda = new javax.swing.JButton();
        ComandaInsert = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        labvel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BuscarComandaID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        AgregarProducto = new javax.swing.JButton();
        ProductoEncontrado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductoID = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TipoProducto = new javax.swing.JComboBox<>();
        Cantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setText("Regresar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Agregar Comanda");

        MesaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MesaID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MesaIDItemStateChanged(evt);
            }
        });
        MesaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesaIDActionPerformed(evt);
            }
        });

        MeseroID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MeseroID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MeseroIDItemStateChanged(evt);
            }
        });

        CajeroID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CajeroID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CajeroIDItemStateChanged(evt);
            }
        });

        AgregarComanda.setText("Agregar Comanda");
        AgregarComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarComandaMouseClicked(evt);
            }
        });

        ComandaInsert.setForeground(new java.awt.Color(51, 255, 51));
        ComandaInsert.setText("Comanda agregada");

        jLabel8.setText("MesaID");

        label1.setText("MeseroID");

        labvel.setText("CajeroID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(label1)
                            .addComponent(labvel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(MeseroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(ComandaInsert))
                            .addComponent(MesaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CajeroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(AgregarComanda))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel6)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MesaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(AgregarComanda))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MeseroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajeroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labvel)))
                    .addComponent(ComandaInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Insertar Productos a comanda");

        jLabel4.setText("ComandaID");

        BuscarComandaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BuscarComandaID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BuscarComandaIDItemStateChanged(evt);
            }
        });

        jLabel2.setText("ProductoID");

        AgregarProducto.setText("Agregar");
        AgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarProductoMouseClicked(evt);
            }
        });
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });

        ProductoEncontrado.setForeground(new java.awt.Color(0, 255, 0));
        ProductoEncontrado.setText("Productos Agregados");

        jLabel5.setText("Cantidad");

        ProductoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProductoID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProductoIDItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo Producto");

        TipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoProductoItemStateChanged(evt);
            }
        });

        Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        Cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CantidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(AgregarProducto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(ProductoEncontrado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarComandaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ProductoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BuscarComandaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(ProductoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(AgregarProducto)
                .addGap(27, 27, 27)
                .addComponent(ProductoEncontrado)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(885, 885, 885)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277)
                .addComponent(jButton5)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Operaciones op = new Operaciones();
        op.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void MesaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesaIDActionPerformed

    private void AgregarComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarComandaMouseClicked


        // TODO add your handling code here:
            
            Statement s;
            try {
                s = conexion.createStatement();
                Conexion bd = new Conexion();
                ResultSet rs;            
                
                System.out.println(this.meseroIDin);
                System.out.println(this.cajeroIDin);
                System.out.println(mesaIDin);
                String query1 = "INSERT INTO Comanda VALUES ("+this.meseroIDin+","+this.cajeroIDin+","+this.mesaIDin+")";
                if(this.contador>0){
                    ComandaInsert.setVisible(true);
                    ComandaInsert.setText("Productos agregados ("+contador+")");
                    ComandaInsert.setForeground(Color.green);
                }
                else{
                    ComandaInsert.setVisible(true);
                    ComandaInsert.setText("Productos agregados");
                    ComandaInsert.setForeground(Color.GREEN);
                }
            contador++;
                int a = s.executeUpdate(query1);
                GenerarComanda Gen = new GenerarComanda();
                Gen.setVisible(true);
                dispose();
                JOptionPane.showMessageDialog(null, "Comanda generada exitosamente");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrió algún error");
                Logger.getLogger(GenerarComanda.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        
    }//GEN-LAST:event_AgregarComandaMouseClicked

    private void MesaIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MesaIDItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getStateChange()==evt.SELECTED){
            MeseroID.removeAllItems();
            System.out.println("HOLAXD");
            try {
                Conexion bd = new Conexion();
                ResultSet rs;
                Statement s;
                s = conexion.createStatement();
                String query = "select EmpleadoID from MeseroAtiendeMesa where MesaID = "+MesaID.getSelectedItem();
                rs = s.executeQuery(query);
                String empleadoID;
                while (rs.next()) {
                    MeseroID.addItem(rs.getString("EmpleadoID"));
                }
                this.mesaIDin = (String) MesaID.getSelectedItem();
            } catch (SQLException ex) {
                Logger.getLogger(GenerarComanda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
    }//GEN-LAST:event_MesaIDItemStateChanged

    private void MeseroIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MeseroIDItemStateChanged
        // TODO add your handling code here:
        this.meseroIDin = (String) MeseroID.getSelectedItem();
    }//GEN-LAST:event_MeseroIDItemStateChanged

    private void CajeroIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CajeroIDItemStateChanged
        // TODO add your handling code here:
        this.cajeroIDin = (String) CajeroID.getSelectedItem();
    }//GEN-LAST:event_CajeroIDItemStateChanged

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void AgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarProductoMouseClicked
        // TODO add your handling code here:
        Conexion bd = new Conexion();
        String id = this.ProductIDin;
        int cantidad = (int) Cantidad.getValue();
        ResultSet rs;
        Statement s;
        if(BuscarComandaID.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "No hay comandas activas");
            return;
        }
        try {
            s = conexion.createStatement();
            String query = "SELECT ProductoID FROM Productos";
            rs = s.executeQuery(query);
            while (rs.next()) {
                if(rs.getString("ProductoID").equals(id)){
                    break;
                }
            }
            System.out.println("HOlAADASDDS");
            String query1 = "select count("+this.ComandaID+") as Linea from DetalleComanda\n" +
            "where ComandaID = "+this.ComandaID;
            rs = s.executeQuery(query1);
            int cuenta = 0;
            while (rs.next()) {
                cuenta = rs.getInt("Linea");
            }
            cuenta++;
            System.out.println("xD");
            System.out.println(cuenta);
            int linea = cuenta;
            query1 = "select ProductoID from Productos where NombreProducto = '"+id+"'";
            rs = s.executeQuery(query1); rs.next();
            int productid = rs.getInt("ProductoID");
            String query2 = "INSERT INTO DetalleComanda\n"+"VALUES ("+this.ComandaID+","+linea+",'"+productid+"',"+cantidad+")";
            System.out.println(ComandaID);
            System.out.println(linea);
            System.out.println(id);
            System.out.println("a");
            System.out.println(cantidad);
            if(this.contador>0){
                ProductoEncontrado.setVisible(true);
                ProductoEncontrado.setText("Productos agregados ("+contador+")");
                ProductoEncontrado.setForeground(Color.green);
            }
            else{
                ProductoEncontrado.setVisible(true);
                ProductoEncontrado.setText("Productos agregados");
                ProductoEncontrado.setForeground(Color.GREEN);
            }
            contador++;
            int elementosInsertados = s.executeUpdate(query2);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió algún error");
            System.out.println(ex);
            ProductoEncontrado.setText("Error");
            ProductoEncontrado.setForeground(Color.red);
        }

    }//GEN-LAST:event_AgregarProductoMouseClicked

    private void BuscarComandaIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BuscarComandaIDItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==evt.SELECTED){
            this.ComandaID = (String) this.BuscarComandaID.getSelectedItem();
        }
    }//GEN-LAST:event_BuscarComandaIDItemStateChanged

    private void ProductoIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProductoIDItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==evt.SELECTED){
            this.ProductIDin = (String) this.ProductoID.getSelectedItem();
        }
    }//GEN-LAST:event_ProductoIDItemStateChanged

    private void TipoProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoProductoItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==evt.SELECTED){
            ProductoID.removeAllItems();
            Conexion bd = new Conexion();
            ResultSet rs;
            Statement s;
            try {
                s = conexion.createStatement();
                String query;
                query = "select * from Productos,TipoProducto where NombreTipoProducto = '"+TipoProducto.getSelectedItem()+"'AND TipoProducto.TipoProductoID = Productos.TipoProductoID";
                rs = s.executeQuery(query);
                while (rs.next()) {
                    System.out.println("XDD");
                    ProductoID.addItem(rs.getString("NombreProducto"));
                }
            this.TipoProductoin = (String) TipoProducto.getSelectedItem();
            } catch (SQLException ex) {
                Logger.getLogger(GenerarComanda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_TipoProductoItemStateChanged

    private void CantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CantidadStateChanged
        // TODO add your handling code here:
        if((int)Cantidad.getValue()<=0){
            Cantidad.setValue(1);
        }
        this.Cantidadin = (int) Cantidad.getValue();
    }//GEN-LAST:event_CantidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarComanda;
    private javax.swing.JButton AgregarProducto;
    private javax.swing.JComboBox<String> BuscarComandaID;
    private javax.swing.JComboBox<String> CajeroID;
    private javax.swing.JSpinner Cantidad;
    private javax.swing.JLabel ComandaInsert;
    private javax.swing.JComboBox<String> MesaID;
    private javax.swing.JComboBox<String> MeseroID;
    private javax.swing.JLabel ProductoEncontrado;
    private javax.swing.JComboBox<String> ProductoID;
    private javax.swing.JComboBox<String> TipoProducto;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labvel;
    // End of variables declaration//GEN-END:variables
}
