/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgregarProductosComanda;

import SQL.CapaPresentacion.Ingresar;
import SQL.CapaPresentacion.Operaciones;
import SQL.Conexion;
import static SQL.Conexion.conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class GenerarTicket extends javax.swing.JFrame {

    /**
     * Creates new form GenerarTicket
     */
    public GenerarTicket() {
        initComponents();
        ComandaID.removeAllItems();
        MetodoPago.removeAllItems();
        MetodoPago.addItem("Efectivo");
        MetodoPago.addItem("Tarjeta");
        
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        
        try {
            s = conexion.createStatement();
            String query = "select * from Comanda where exists (select * from DetalleComanda where DetalleComanda.ComandaID = Comanda.ComandaID) and Not exists (Select * from Ticket where Ticket.ComandaID = Comanda.ComandaID)";
            rs = s.executeQuery(query);
            
            while (rs.next()) {
                ComandaID.addItem(rs.getString("ComandaID"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GenerarTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        ComandaID = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RealizarTicket = new javax.swing.JButton();
        MetodoPago = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComandaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("RealizarTicket");

        jLabel2.setText("ComandaID");

        RealizarTicket.setText("Realizar");
        RealizarTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RealizarTicketMouseClicked(evt);
            }
        });
        RealizarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarTicketActionPerformed(evt);
            }
        });

        MetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MetodoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MetodoPagoItemStateChanged(evt);
            }
        });

        jLabel5.setText("Metodo Pago");

        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComandaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RealizarTicket)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComandaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(MetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RealizarTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RealizarTicketActionPerformed

    private void RealizarTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RealizarTicketMouseClicked
        // TODO add your handling code here:
        String ticketID;
        String fecha;
        String metodoPago = (String) MetodoPago.getSelectedItem();
        String comandaID = (String) ComandaID.getSelectedItem();
        int empleadoID=0;
        float pagoTotal;
        
        Conexion bd = new Conexion();
        ResultSet rs;
        Statement s;
        System.out.println(metodoPago);
        System.out.println(comandaID);
        fecha = Ingresar.devolverFecha();
        System.out.println(fecha);
        //////////////////////////
        
        //////////////////////////
        try {
            s = conexion.createStatement();
            //////////////////////////////////
            /*
            String query2 = "SELECT decom.ComandaID, decom.Linea, decom.ProductoID , decom.Cantidad, SUM(decom.Cantidad*pr.PrecioUnidad) TotalLinea FROM Productos pr, DetalleComanda decom \n" +
"WHERE decom.ProductoID=pr.ProductoID AND ComandaID = "+comandaID+"\n" +
"GROUP BY decom.ComandaID, decom.Linea, decom.ProductoID, decom.Cantidad ";
            
            ResultSet r; //rs
            Statement ser;//s
            ser = conexion.createStatement();
            r = ser.executeQuery(query2);
            
            
            System.out.println("funciono");
            while(r.next()){
                int a = s.executeUpdate("INSERT INTO DetalleTicket\n" +
                "VALUES ("+comandaID+","+comandaID+","+r.getInt("Linea")+","+r.getInt("ProductoID")+","+r.getInt("Cantidad")+","+r.getInt("TotalLinea")+")");
                System.out.println("aaa");
            }
            /////////////////////////////////*/
            String query = "select * from Comanda where ComandaID = "+comandaID;
            rs = s.executeQuery(query);
            while(rs.next()){
                empleadoID = rs.getInt("MeseroID");
                System.out.println(empleadoID);
            }
            query = "SELECT dcom.ComandaID, SUM(dcom.Cantidad*pr.PrecioUnidad) Total FROM DetalleComanda dcom, Productos pr\n" +
            "WHERE dcom.ProductoID=pr.ProductoID AND ComandaID = "+comandaID+"\n" +
            "GROUP BY dcom.ComandaID";
            rs = s.executeQuery(query);
            rs.next();
            pagoTotal = rs.getFloat("Total");
            System.out.println(pagoTotal);
            //error tal vez quitar ticketID
            query = "INSERT INTO Ticket\n" + "VALUES ("+pagoTotal+",'"+fecha+"','"+metodoPago+"',"+comandaID+","+empleadoID+")";
            int a = s.executeUpdate(query);
            System.out.println("Todobienn");
            String query2 = "SELECT decom.ComandaID, decom.Linea, decom.ProductoID , decom.Cantidad, SUM(decom.Cantidad*pr.PrecioUnidad) TotalLinea FROM Productos pr, DetalleComanda decom \n" +
"WHERE decom.ProductoID=pr.ProductoID AND ComandaID = "+comandaID+"\n" +
"GROUP BY decom.ComandaID, decom.Linea, decom.ProductoID, decom.Cantidad ";
            rs = s.executeQuery("select Top(1) max(TicketID) as Maximo from Ticket ");
            rs.next();
            ticketID = rs.getString("Maximo");
            ResultSet r; //rs
            Statement ser;//s
            ser = conexion.createStatement();
            r = s.executeQuery(query2);
            
            query = "INSERT INTO DetalleTicket\n" +
                "VALUES ("+comandaID+","+comandaID+","+comandaID+",cantidad,precio)";
            
            
            while(r.next()){
                a = ser.executeUpdate("INSERT INTO DetalleTicket\n" +
                "VALUES ("+ticketID+","+comandaID+","+r.getInt("Linea")+","+r.getInt("ProductoID")+","+r.getInt("Cantidad")+","+r.getInt("TotalLinea")+")");
                System.out.println("aaa");
            }
            JOptionPane.showMessageDialog(null, "Ticket Generado exitosamente!");
            GenerarTicket gen = new GenerarTicket();
            gen.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(GenerarTicket.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrió algún error");
        }
    }//GEN-LAST:event_RealizarTicketMouseClicked

    private void MetodoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MetodoPagoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MetodoPagoItemStateChanged

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        Operaciones op = new Operaciones();
        op.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComandaID;
    private javax.swing.JComboBox<String> MetodoPago;
    private javax.swing.JButton RealizarTicket;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
