/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Consultas;

import SQL.CapaPresentacion.Menu;
import SQL.Conexion;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author GUILLERMO
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    private Conexion bd;
    
    public Consultas() throws SQLException {
        initComponents();
        
        bd = new Conexion();
        String[] tableColumnsName = {"Ticket ID","Descripcion","Pago Total","Fecha","Metodo Pago","Comanda ID","Cajero ID"};
        DefaultTableModel aModel = (DefaultTableModel) jTable1.getModel();
        aModel.setColumnIdentifiers(tableColumnsName);
        ResultSet rs = bd.Catalogo(7);
        
        //We loop through ResultSet, as usual.
        ResultSetMetaData rsmd = rs.getMetaData();
        int colNo = rsmd.getColumnCount();
        while(rs.next()){
            Object[] objects = new Object[colNo];
            
            for(int i=0;i<colNo;i++){
                objects[i] = rs.getObject(i+1);
            }
            aModel.addRow(objects);
        }
        jTable1.setModel (aModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        BotonRegreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        diaTextField = new javax.swing.JTextField();
        fechaCheckbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        mesTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anioTextField = new javax.swing.JTextField();
        empleadoIDCheckbox = new javax.swing.JCheckBox();
        empleadoIDTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ascendenteRadioButton = new javax.swing.JRadioButton();
        descendenteRadioButton = new javax.swing.JRadioButton();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SingleFechaRadioButton = new javax.swing.JRadioButton();
        DuoFechaRadioButton = new javax.swing.JRadioButton();
        diaTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mesTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anioTextField2 = new javax.swing.JTextField();
        anteriorRadioButton = new javax.swing.JRadioButton();
        posteriorRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonRegreso.setText("Regresar");
        BotonRegreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Parámetros de Búsqueda:");

        diaTextField.setEnabled(false);
        diaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTextFieldActionPerformed(evt);
            }
        });

        fechaCheckbox.setText("Por fecha:");
        fechaCheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaCheckboxMouseClicked(evt);
            }
        });
        fechaCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCheckboxActionPerformed(evt);
            }
        });

        jLabel2.setText("/");

        mesTextField.setEnabled(false);
        mesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("/");

        anioTextField.setEnabled(false);
        anioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioTextFieldActionPerformed(evt);
            }
        });

        empleadoIDCheckbox.setText("Por empleado ID:");
        empleadoIDCheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadoIDCheckboxMouseClicked(evt);
            }
        });

        empleadoIDTextField.setEnabled(false);

        jLabel4.setText("Orden:");

        buttonGroup1.add(ascendenteRadioButton);
        ascendenteRadioButton.setSelected(true);
        ascendenteRadioButton.setText("Ascendente");

        buttonGroup1.add(descendenteRadioButton);
        descendenteRadioButton.setText("Descendente");

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.setToolTipText("");
        buscarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarButtonMouseClicked(evt);
            }
        });
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonGroup2.add(SingleFechaRadioButton);
        SingleFechaRadioButton.setText("Una fecha");
        SingleFechaRadioButton.setEnabled(false);
        SingleFechaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleFechaRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(DuoFechaRadioButton);
        DuoFechaRadioButton.setText("Entre dos fechas");
        DuoFechaRadioButton.setEnabled(false);
        DuoFechaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuoFechaRadioButtonActionPerformed(evt);
            }
        });

        diaTextField2.setEnabled(false);
        diaTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("/");

        mesTextField2.setEnabled(false);
        mesTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setText("/");

        anioTextField2.setEnabled(false);
        anioTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioTextField2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(anteriorRadioButton);
        anteriorRadioButton.setSelected(true);
        anteriorRadioButton.setText("Anterior");
        anteriorRadioButton.setEnabled(false);
        anteriorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup3.add(posteriorRadioButton);
        posteriorRadioButton.setText("Posterior");
        posteriorRadioButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegreso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaCheckbox))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(empleadoIDCheckbox)))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(925, 925, 925)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(diaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anioTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DuoFechaRadioButton)
                            .addComponent(jLabel4)
                            .addComponent(ascendenteRadioButton)
                            .addComponent(descendenteRadioButton)
                            .addComponent(empleadoIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SingleFechaRadioButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anteriorRadioButton)
                                    .addComponent(posteriorRadioButton))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fechaCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SingleFechaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anteriorRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(posteriorRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DuoFechaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(mesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(anioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(mesTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(anioTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empleadoIDCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empleadoIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ascendenteRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descendenteRadioButton)
                        .addGap(31, 31, 31)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(BotonRegreso)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresoMouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresoMouseClicked

    private void diaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaTextFieldActionPerformed

    private void fechaCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCheckboxActionPerformed

    private void mesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesTextFieldActionPerformed

    private void anioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioTextFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        
        String dia = diaTextField.getText();
        String mes = mesTextField.getText();
        String anio = anioTextField.getText();
        String dia2 = diaTextField2.getText();
        String mes2 = mesTextField2.getText();
        String anio2 = anioTextField2.getText();
        int leapYearCheck;
        String dateQuery = null;
        
        String id = empleadoIDTextField.getText();
        String idQuery = null;
        
        int parametersAmount = 0;
        
        String orderQuery;
        String Query = null;
        
        if(fechaCheckbox.isSelected()){
            if(dia.equals("") || mes.equals("") || anio.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Inserte la fecha que se desea buscar.");
                return;
            } else {
                try {
                    int d = Integer.parseInt(dia);
                    int m = Integer.parseInt(mes);
                    int y = Integer.parseInt(anio);
                    
                    if(DuoFechaRadioButton.isSelected())
                    {
                        if(dia2.equals("") || mes2.equals("") || anio2.equals("")){
                            JOptionPane.showMessageDialog(null, "Inserte la segunda fecha que desea buscar.");
                        } else {
                            try {
                                int d2 = Integer.parseInt(dia2);
                                int m2 = Integer.parseInt(mes2);
                                int y2 = Integer.parseInt(anio2);
                                
                                if(m2 < 1 || m2 > 12) {
                                    JOptionPane.showMessageDialog(null, "Inserte un mes válido en la segunda fecha.");
                                    return;
                                } else if(y2 < 1900) {
                                    JOptionPane.showMessageDialog(null, "Inserte un segundo añó válido.");
                                    return;
                                }
                                
                                leapYearCheck = Math.floorMod(y2, 4);
                                
                                switch(m2) {
                                    case 1:
                                    case 3:
                                    case 5:
                                    case 7:
                                    case 8:
                                    case 10:
                                    case 12:
                                        if(d2 < 1 || d2 > 31) {
                                            JOptionPane.showMessageDialog(null, "Inserte un día válido en la segunda fecha. Entre 1 y 31.");
                                            return;
                                        }   break;
                                    case 4:
                                    case 6:
                                    case 9:
                                    case 11:
                                        if(d2 < 1 || d2 > 30) {
                                            JOptionPane.showMessageDialog(null, "Inserte un día válido en la segunda fecha. Entre 1 y 30.");
                                            return;
                                        }   break;
                                    case 2:
                                        if(leapYearCheck == 0) {
                                            if(d2 < 1 || d2 > 29) {
                                                JOptionPane.showMessageDialog(null, "Inserte un dia válido en la segunda fecha. Entre 1 y 29.");
                                                return;
                                            }
                                        } else {
                                            if(d2 < 1 || d2 > 28) {
                                                JOptionPane.showMessageDialog(null, "Inserte un dia válido en la segunda fecha. Entre 1 y 28.");
                                                return;
                                            }
                                        }   break;
                                }
                            } catch (HeadlessException | NumberFormatException e) {
                                JOptionPane.showMessageDialog(null, "Asegúrese que los valores sean válidos dentro de la segunda fecha.");
                            }
                        }
                    }
                    
                    if(m < 1 || m > 12) {
                        JOptionPane.showMessageDialog(null, "Inserte un mes válido.");
                        return;
                    } else if (y < 1900) {
                        JOptionPane.showMessageDialog(null, "Inserte un año válido.");
                        return;
                    }
                    
                    leapYearCheck = Math.floorMod(y, 4);
                    
                    switch(m){
                        case 1:
                        case 3:
                        case 5:
                        case 7:
                        case 8:
                        case 10:
                        case 12:
                            if(d < 1 || d > 31) {
                                JOptionPane.showMessageDialog(null, "Inserte un día válido en la fecha. Entre 1 y 31.");
                                return;
                            }   break;
                        case 4:
                        case 6:
                        case 9:
                        case 11:
                            if(d < 1 || d > 30) {
                                JOptionPane.showMessageDialog(null, "Inserte un día válido en la fecha. Entre 1 y 30.");
                                return;
                            } break;
                        case 2:
                            if(leapYearCheck == 0)
                            {
                                if(d < 1 || d > 29) {
                                    JOptionPane.showMessageDialog(null, "Inserte un día válido en la fecha. Entre 1 y 29.");
                                    return;
                                }
                            } else {
                                if(d < 1 || d > 28) {
                                    JOptionPane.showMessageDialog(null, "Inserte un día válido en la fecha. Entre 1 y 28.");
                                    return;
                                }
                            }   break;
                    }
                    
                    
                } catch(HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Asegúrese que los valores sean válidos dentro de la fecha.");
                    return;
                }
            }
            
            //make query line HERE
            if(DuoFechaRadioButton.isSelected()) {
                dateQuery = "(Fecha BETWEEN '" + anio + "-" + mes + "-" + dia + "' AND '" 
                                + anio2 + "-" + mes2 + "-" + dia2 + "')";
            } else {
                if(anteriorRadioButton.isSelected()) {
                    dateQuery = "(Fecha < '" + anio + "-" + mes + "-" + dia + "')";
                } else {
                    dateQuery = "(Fecha > '" + anio + "-" + mes + "-" + dia + "')";
                }
            }
            
            parametersAmount++;
        }
        
        if(empleadoIDCheckbox.isSelected()) {
            if(id.equals("")) {
                JOptionPane.showMessageDialog(null, "Inserte un ID del Empleado a buscar.");
                return;
            } else {
                try {
                    int ID = Integer.parseInt(id);
                    
                    if (ID < 1) {
                        JOptionPane.showMessageDialog(null, "El ID Empleado no puede ser menor a 1.");
                        return;
                    }
                    
                } catch (HeadlessException | NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Asegúrese que el ID Empleado es un valor válido.");
                    return;
                }
            }
            
            //make query line HERE
            idQuery = "(EmpleadoID = " + id + ")";
            
            parametersAmount++;
        }
        
        if(ascendenteRadioButton.isSelected()) {
            orderQuery = "ASC";
        } else {
            orderQuery = "DESC";
        }
        
        switch (parametersAmount) {
            case 0:
                Query = "SELECT * FROM Ticket ORDER BY TicketID " + orderQuery;
                break;
            case 1:
                if(fechaCheckbox.isSelected()) {
                    Query = "SELECT * FROM Ticket WHERE " + dateQuery + " ORDER BY Fecha " + orderQuery;
                } else {
                    Query = "SELECT * FROM Ticket WHERE " + idQuery + " ORDER BY EmpleadoID " + orderQuery;
                }   break;
            case 2:
                Query = "SELECT * FROM Ticket WHERE " + dateQuery + " AND " + idQuery +
                        " ORDER BY Fecha " + orderQuery + ", EmpleadoID " + orderQuery;
                break;
            default:
                break;
        }
        
        bd = new Conexion();
        String[] tableColumnsName = {"Ticket ID","Descripcion","Pago Total","Fecha","Metodo Pago","Comanda ID","Cajero ID"};
        DefaultTableModel aModel = (DefaultTableModel) jTable1.getModel();
        aModel.setColumnIdentifiers(tableColumnsName);
        ResultSet rs = bd.ConsultarBusqueda(Query);
        
        //We loop through ResultSet, as usual.
        ResultSetMetaData rsmd = null;
        try {
            rsmd = rs.getMetaData();
        } catch (SQLException ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        int colNo = 0;
        try {
            colNo = rsmd.getColumnCount();
        } catch (SQLException ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
                Object[] objects = new Object[colNo];
                
                for(int i=0;i<colNo;i++){
                    objects[i] = rs.getObject(i+1);
                }
                aModel.addRow(objects);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel (aModel);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void fechaCheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaCheckboxMouseClicked
        // TODO add your handling code here:
        if(fechaCheckbox.isSelected()){
            diaTextField.setEnabled(true);
            mesTextField.setEnabled(true);
            anioTextField.setEnabled(true);
            SingleFechaRadioButton.setEnabled(true);
            DuoFechaRadioButton.setEnabled(true);
            SingleFechaRadioButton.setSelected(true);
        } else {
            diaTextField.setEnabled(false);
            mesTextField.setEnabled(false);
            anioTextField.setEnabled(false);
            SingleFechaRadioButton.setEnabled(false);
            DuoFechaRadioButton.setEnabled(false);
            SingleFechaRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_fechaCheckboxMouseClicked

    private void empleadoIDCheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadoIDCheckboxMouseClicked
        // TODO add your handling code here:
        if(empleadoIDCheckbox.isSelected()){
            empleadoIDTextField.setEnabled(true);
        } else {
            empleadoIDTextField.setEnabled(false);
        }
    }//GEN-LAST:event_empleadoIDCheckboxMouseClicked

    private void buscarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButtonMouseClicked

    private void diaTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaTextField2ActionPerformed

    private void mesTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesTextField2ActionPerformed

    private void anioTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioTextField2ActionPerformed

    private void anteriorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anteriorRadioButtonActionPerformed

    private void SingleFechaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleFechaRadioButtonActionPerformed
        // TODO add your handling code here:
        anteriorRadioButton.setEnabled(true);
        posteriorRadioButton.setEnabled(true);
        diaTextField2.setEnabled(false);
        mesTextField2.setEnabled(false);
        anioTextField2.setEnabled(false);
    }//GEN-LAST:event_SingleFechaRadioButtonActionPerformed

    private void DuoFechaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuoFechaRadioButtonActionPerformed
        // TODO add your handling code here:
        anteriorRadioButton.setEnabled(false);
        posteriorRadioButton.setEnabled(false);
        diaTextField2.setEnabled(true);
        mesTextField2.setEnabled(true);
        anioTextField2.setEnabled(true);
    }//GEN-LAST:event_DuoFechaRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Consultas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegreso;
    private javax.swing.JRadioButton DuoFechaRadioButton;
    private javax.swing.JRadioButton SingleFechaRadioButton;
    private javax.swing.JTextField anioTextField;
    private javax.swing.JTextField anioTextField2;
    private javax.swing.JRadioButton anteriorRadioButton;
    private javax.swing.JRadioButton ascendenteRadioButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton descendenteRadioButton;
    private javax.swing.JTextField diaTextField;
    private javax.swing.JTextField diaTextField2;
    private javax.swing.JCheckBox empleadoIDCheckbox;
    private javax.swing.JTextField empleadoIDTextField;
    private javax.swing.JCheckBox fechaCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mesTextField;
    private javax.swing.JTextField mesTextField2;
    private javax.swing.JRadioButton posteriorRadioButton;
    // End of variables declaration//GEN-END:variables
}
