/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQL.CapaPresentacion;

import AgregarProductosComanda.GenerarComanda;
import AgregarProductosComanda.GenerarFactura;
import AgregarProductosComanda.GenerarTicket;
import Alterar.AlterarClientes;
import Alterar.AlterarMenu;
import SQL.Conexion;
import java.sql.SQLException;

/**
 *
 * @author Giovanny Vargas
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
        ValidacionPuesto();
    }
    private Conexion bd;
    private void ValidacionPuesto(){
         bd = new Conexion();
         int puesto = bd.ObtenerPuestoID();
         switch(puesto){
             case 1: BotonAlterar.setEnabled(false);
             case 2: break;
             case 3: BotonAlterar.setEnabled(false);
                     BotonTicket.setEnabled(false);
                     BotonFactura.setEnabled(false);
                     break;
             case 4: BotonAlterar.setEnabled(false);
                     BotonComanda.setEnabled(false);
                     break;
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonComanda = new javax.swing.JButton();
        BotonTicket = new javax.swing.JButton();
        BotonFactura = new javax.swing.JButton();
        BotonAlterar = new javax.swing.JButton();
        BotonRegresoConsultas1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonComanda.setText("Generar comanda");
        BotonComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonComandaMouseClicked(evt);
            }
        });
        BotonComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComandaActionPerformed(evt);
            }
        });

        BotonTicket.setText("Generar Ticket");
        BotonTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTicketActionPerformed(evt);
            }
        });

        BotonFactura.setText("Generar Factura");
        BotonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFacturaActionPerformed(evt);
            }
        });

        BotonAlterar.setText("Alterar");
        BotonAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAlterarMouseClicked(evt);
            }
        });
        BotonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlterarActionPerformed(evt);
            }
        });

        BotonRegresoConsultas1.setText("Regresar");
        BotonRegresoConsultas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresoConsultas1MouseClicked(evt);
            }
        });
        BotonRegresoConsultas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresoConsultas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(BotonComanda)
                .addGap(77, 77, 77)
                .addComponent(BotonTicket)
                .addGap(77, 77, 77)
                .addComponent(BotonFactura)
                .addGap(173, 173, 173)
                .addComponent(BotonAlterar)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegresoConsultas1)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonComanda)
                    .addComponent(BotonTicket)
                    .addComponent(BotonFactura)
                    .addComponent(BotonAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(BotonRegresoConsultas1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAlterarMouseClicked
        // TODO add your handling code here:
        //Leave it to me!
    }//GEN-LAST:event_BotonAlterarMouseClicked

    private void BotonRegresoConsultas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresoConsultas1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegresoConsultas1MouseClicked

    private void BotonComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComandaMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BotonComandaMouseClicked

    private void BotonTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTicketActionPerformed
        // TODO add your handling code here:
        GenerarTicket ticket = new GenerarTicket();
        ticket.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonTicketActionPerformed

    private void BotonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFacturaActionPerformed
        // TODO add your handling code here:
        GenerarFactura fac = new GenerarFactura();
        fac.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonFacturaActionPerformed

    private void BotonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlterarActionPerformed
        // TODO add your handling code here:
        AlterarMenu MenuAlterar = new AlterarMenu();
        MenuAlterar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAlterarActionPerformed

    private void BotonComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComandaActionPerformed
        // TODO add your handling code here:
         GenerarComanda comanda = new GenerarComanda();
        comanda.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonComandaActionPerformed

    private void BotonRegresoConsultas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresoConsultas1ActionPerformed
        // TODO add your handling code here:
         Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresoConsultas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlterar;
    private javax.swing.JButton BotonComanda;
    private javax.swing.JButton BotonFactura;
    private javax.swing.JButton BotonRegresoConsultas1;
    private javax.swing.JButton BotonTicket;
    // End of variables declaration//GEN-END:variables
}
